# Site settings
title: Lotfollahi
description: I'm Baran Lotfollahi, a portrait photographer and illustrator based in Iran. <a href="https://unsplash.com/@baranlotfollahi">my unsplash</a>
baseurl: "/lens-jekyll-theme" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Ursala

# Collection settings
collections:
  photos:

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: 

# Build settings
markdown: kramdown
